<?php

namespace Cron\CronBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CronReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronReportRepository extends EntityRepository
{
}
